# Autogenerated wrapper script for ChronoCxx_jll for x86_64-linux-gnu-cxx11-julia_version+1.11.1
export libchrono_cxx

using libcxxwrap_julia_jll
using Chrono_jll
using VulkanSceneGraph_jll
JLLWrappers.@generate_wrapper_header("ChronoCxx")
JLLWrappers.@declare_library_product(libchrono_cxx, "libchrono_cxx.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, Chrono_jll, VulkanSceneGraph_jll)
    JLLWrappers.@init_library_product(
        libchrono_cxx,
        "lib/libchrono_cxx.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
